//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkBBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class factura
    {
        public factura()
        {
            this.factura_detall = new HashSet<factura_detall>();
        }
    
        public int n_factura { get; set; }
        public int id_client { get; set; }
        public System.DateTime data { get; set; }
        public int descompte { get; set; }
        public int iva { get; set; }
    
        public virtual client client { get; set; }
        public virtual ICollection<factura_detall> factura_detall { get; set; }
    }
}
