//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkBBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class factura_detall
    {
        public int n_factura { get; set; }
        public int id_producte { get; set; }
        public int quantitat { get; set; }
    
        public virtual factura factura { get; set; }
        public virtual producte producte { get; set; }
    }
}
