//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkBBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class producte
    {
        public producte()
        {
            this.factura_detall = new HashSet<factura_detall>();
        }
    
        public int id_producte { get; set; }
        public string producte1 { get; set; }
        public decimal preu { get; set; }
    
        public virtual ICollection<factura_detall> factura_detall { get; set; }
    }
}
