//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkBBD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dam_m06_entity_frameworkEntities : DbContext
    {
        public dam_m06_entity_frameworkEntities()
            : base("name=dam_m06_entity_frameworkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<client> clients { get; set; }
        public DbSet<factura> facturas { get; set; }
        public DbSet<producte> productes { get; set; }
        public DbSet<test> tests { get; set; }
        public DbSet<factura_detall> factura_detall { get; set; }
    }
}
